config/routes.rb
Rails.application.routes.draw do
  resources :xurs
  resources :tds

  root "projects#index"

  devise_for :users
  
  resources :mboards
  
  resources :mbs
  
  resources :projects do
    
    resources :mboards

    resources :tds
     
    resources :xurs
    
  end
  
end

app/models/mb.rb
class Mb < ApplicationRecord
  belongs_to :mboard
end
 

app/controllers/mbs_controller.rb
class MbsController < ApplicationController
  before_action :set_mb, only: %i[ show edit update destroy ]

  # GET /mbs or /mbs.json
  def index
    @mbs = Mb.all
  end
 
  # GET /mbs/1 or /mbs/1.json
  def show
  end

  # GET /mbs/new
  def new
    @mb = Mb.new
  end

  # GET /mbs/1/edit
  def edit
  end

  # POST /mbs or /mbs.json
  def create
    @mb = Mb.new(mb_params)

    respond_to do |format|
      if @mb.save
        format.html { redirect_to mboard_path(@mb.mboard) }
        format.json { render :show, status: :created, location: @mb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mbs/1 or /mbs/1.json
  def update
    respond_to do |format|
      if @mb.update(mb_params)
        format.html { redirect_to mb_url(@mb), notice: "Mb was successfully updated." }
        format.json { render :show, status: :ok, location: @mb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mbs/1 or /mbs/1.json
  def destroy
    @mb.destroy
    redirect_to mboard_path(@mb.mboard)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mb
      @mb = Mb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mb_params
      params.require(:mb).permit(:body, :mboard_id)
    end
end

app/helpers/mbs_helper.rb
module MbsHelper
end
 

app/views/mbs/_form.html.erb
<%= form_with(model: mb) do |form| %>
    <%= form.text_field :body %>
    <%= form.text_field :mboard_id %>
    <%= form.submit %>
<% end %>
 

app/views/mbs/_mb.html.erb
<div id="<%= dom_id mb %>">
  <p>
    <strong>Body:</strong>
    <%= mb.body %>
  </p>
 
  <p>
    <strong>Mboard:</strong>
    <%= mb.mboard_id %>
  </p>

</div>

app/views/mbs/edit.html.erb
<h1>Editing mb</h1>

<%= render "form", mb: @mb %>

<br>

<div>
  <%= link_to "Show this mb", @mb %> |
  <%= link_to "Back to mbs", mbs_path %>
</div>
 

app/views/mbs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mbs</h1>

<div id="mbs">
  <% @mbs.each do |mb| %>
    <%= render mb %>
    <p>
      <%= link_to "Show this mb", mb %>
    </p>
  <% end %>
</div>

<%= link_to "New mb", new_mb_path %>
 

app/views/mbs/new.html.erb
<h1>New mb</h1>

<%= render "form", mb: @mb %>

<br>

<div>
  <%= link_to "Back to mbs", mbs_path %>
</div>
 

app/views/mbs/show.html.erb
<%= render @mb %>

<div>
  <%= link_to "Edit this mb", edit_mb_path(@mb) %> |
  <%= link_to "Back to mbs", mbs_path %>
  <%= button_to "Destroy this mb", @mb, method: :delete %>
</div>
 