config/routes.rb
Rails.application.routes.draw do
  resources :xurs
  resources :tds

  root "projects#index"

  devise_for :users
  
  resources :mboards
  
  resources :mbs
  
  resources :projects do
    
    resources :mboards

    resources :tds
     
    resources :xurs
    
  end
  
end

app/models/td.rb
class Td < ApplicationRecord
  belongs_to :project
end
 

app/controllers/tds_controller.rb
class TdsController < ApplicationController
  before_action :set_td, only: %i[ show edit update destroy ]

  def index
    @project = Project.find(params[:project_id])
    @tds = @project.tds 
    @td = @project.tds.new
  end
 
  def show
  end

  def new
    @project = Project.find(params[:project_id])
    @td = @project.tds.new
  end

  def edit
  end

  def create
    @td = Td.new(td_params)

    respond_to do |format|
      if @td.save
        format.html { redirect_to project_tds_url(@td.project_id), notice: "Td was successfully created." }
        format.json { render :show, status: :created, location: @td }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @td.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @td.update(td_params)
        format.html { redirect_to project_tds_url(@td.project_id), notice: "Td was successfully updated." }
        format.json { render :show, status: :ok, location: @td }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @td.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @td.destroy

    redirect_to project_tds_url(@td.project_id)
 
  end

  private
    def set_td
      @td = Td.find(params[:id])
    end

    def td_params
      params.require(:td).permit(:name, :project_id)
    end
end

app/helpers/tds_helper.rb
module TdsHelper
end
 

app/views/tds/_form.html.erb
<div class="container__item">
    <%= form_with(model: td, class: "form") do |form| %>
      <%= form.text_field :name, class:"form__field"%>
      <%= form.submit class:"btn btn--primary btn--inside uppercase"%>
    <% end %>
</div>
 

app/views/tds/_td.html.erb
<div id="<%= dom_id td %>">
  <p>
    <strong>Name:</strong>
    <%= td.name %>
  </p>


</div>
 

app/views/tds/edit.html.erb
<h1>Editing td</h1>

<%= render "form", td: @td %>

<br>

<div>
  <%= link_to "Back to tds", project_tds_path(@td.project) %>
</div>
 
<style>
  :root {
  background: #f5f6fa;
  color: #9c9c9c;
  font: 1rem "PT Sans", sans-serif;
}

html,
body,
.container {
  height: 100%;
}

a {
  color: inherit;
}
a:hover {
  color: #7f8ff4;
}

.container {
  flex-direction: column;
  align-items: left;
  justify-content: center;
}

.uppercase {
  text-transform: uppercase;
}

.btn {
  display: inline-block;
  background: transparent;
  color: inherit;
  font: inherit;
  border: 0;
  outline: 0;
  padding: 0;
  transition: all 200ms ease-in;
  cursor: pointer;
}
.btn--primary {
  background: #7f8ff4;
  color: #fff;
  box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1);
  border-radius: 2px;
  padding: 12px 36px;
}
.btn--primary:hover {
  background: #6c7ff2;
}
.btn--primary:active {
  background: #7f8ff4;
  box-shadow: inset 0 0 10px 2px rgba(0, 0, 0, 0.2);
}
.btn--inside {
  margin-left: -96px;
}

.form__field {
  width: 360px;
  background: #fff;
  color: #a3a3a3;
  font: inherit;
  box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1);
  border: 0;
  outline: 0;
  padding: 22px 18px;
}

</style>

app/views/tds/index.html.erb
<h1>Tds</h1>


	<div class="container__item">
    <%= form_with(model: @td, class: "form") do |form| %>
      <%= form.text_field :name, class:"form__field"%>
      <%= form.submit class:"btn btn--primary btn--inside uppercase"%>
		  <%= form.text_field :project_id, type: :hidden %>
    <% end %>
	</div>
 


<div id="tds">
  <% @tds.each do |todo| %>
    <p><%= todo.name %></p>
    <% if todo.name %>
        <%= link_to "Edit", edit_project_td_path(todo.project, todo) %> |
        <%= link_to "Destroy", todo, "data-turbo-method": :delete %>
    <% end %>
  <% end %>
</div>

<%= link_to "Back", project_path(@project) %>

<style>
  :root {
  background: #f5f6fa;
  color: #9c9c9c;
  font: 1rem "PT Sans", sans-serif;
}

html,
body,
.container {
  height: 100%;
}

a {
  color: inherit;
}
a:hover {
  color: #7f8ff4;
}

.container {
  flex-direction: column;
  align-items: left;
  justify-content: center;
}

.uppercase {
  text-transform: uppercase;
}

.btn {
  display: inline-block;
  background: transparent;
  color: inherit;
  font: inherit;
  border: 0;
  outline: 0;
  padding: 0;
  transition: all 200ms ease-in;
  cursor: pointer;
}
.btn--primary {
  background: #7f8ff4;
  color: #fff;
  box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1);
  border-radius: 2px;
  padding: 12px 36px;
}
.btn--primary:hover {
  background: #6c7ff2;
}
.btn--primary:active {
  background: #7f8ff4;
  box-shadow: inset 0 0 10px 2px rgba(0, 0, 0, 0.2);
}
.btn--inside {
  margin-left: -96px;
}

.form__field {
  width: 360px;
  background: #fff;
  color: #a3a3a3;
  font: inherit;
  box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1);
  border: 0;
  outline: 0;
  padding: 22px 18px;
}

</style>

app/views/tds/new.html.erb
<h1>New td</h1>

<%= render "form", td: @td %>

<br>

<div>
  <%= link_to "Back to tds", tds_path %>
</div>
 

app/views/tds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @td %>

<div>
  <%= link_to "Edit this td", edit_td_path(@td) %> |
  <%= link_to "Back to tds", tds_path %>

  <%= button_to "Destroy this td", @td, method: :delete %>
</div>
 