config/routes.rb
Rails.application.routes.draw do
  resources :xurs
  resources :tds

  root "projects#index"

  devise_for :users
  
  resources :mboards
  
  resources :mbs
  
  resources :projects do
    
    resources :mboards

    resources :tds
     
    resources :xurs
    
  end
  
end

app/models/mboard.rb
class Mboard < ApplicationRecord
  belongs_to :project
  has_many :mbs, dependent: :destroy
end
 

app/controllers/mboards_controller.rb
class MboardsController < ApplicationController
  before_action :set_mboard, only: %i[ show edit update destroy ]

  # GET /mboards or /mboards.json
  def index
    @project = Project.find(params[:project_id])
    @mboards = Mboard.all
  end
 
  # GET /mboards/1 or /mboards/1.json
  def show
    @mb = @mboard.mbs.new
    @mbs = @mboard.mbs
  end

  # GET /mboards/new
  def new
    @pr = Project.find(params[:project_id])
    @mboard = @pr.mboards.new
  end

  # GET /mboards/1/edit
  def edit
  end

  # POST /mboards or /mboards.json
  def create
    @mboard = Mboard.new(mboard_params)

    respond_to do |format|
      if @mboard.save
        format.html { redirect_to project_mboards_path(@mboard.project_id), notice: "Mboard was successfully created." }
        format.json { render :show, status: :created, location: @mboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mboards/1 or /mboards/1.json
  def update
    respond_to do |format|
      if @mboard.update(mboard_params)
        format.html { redirect_to mboard_url(@mboard), notice: "Mboard was successfully updated." }
        format.json { render :show, status: :ok, location: @mboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mboards/1 or /mboards/1.json
  def destroy
    @mboard.destroy

    respond_to do |format|
      format.html { redirect_to project_mboards_url(@mboard.project), notice: "Mboard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mboard
      @mboard = Mboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mboard_params
      params.require(:mboard).permit(:name, :body, :project_id)
    end
end

app/helpers/mboards_helper.rb
module MboardsHelper
end
 

app/views/mboards/_form.html.erb
<div class="container">
  <%= form_with(model: mboard) do |form| %>

		<div class="field" tabindex="1">
			<label for="username">
				<i class="far fa-user"></i> Name
			</label>
       <%= form.text_field :name, type:"text", placeholder:"text"%>
		</div>
		<div class="field" tabindex="2">
			<label for="email">
				<i class="far fa-envelope"></i> Body
			</label>
       <%= form.text_field :body, type:"text", placeholder:"text" %>
		</div>
     <%= form.text_field :project_id, type: :hidden %>
		<%= form.submit class: "button"%>
    </div>
<% end %>
</div> 

<style>
  @import url("https://fonts.googleapis.com/css?family=Saira+Semi+Condensed&display=swap");
* {
  font-family: "Saira Semi Condensed", sans-serif;
  transition: all 0.5s ease;
}

body {
  background: #dfdfdf;
}

.container {
  width: 100%;
  height: 100%;
  padding: 0 16px;
  display: flex;
  flex-flow: row nowrap;
  align-items: center;
  justify-content: center;
}

form {
  width: 400px;
  display: flex;
  flex-flow: column wrap;
  align-items: center;
  justify-content: center;
}
form div, form label, form input, form textarea {
  width: 100%;
}

.field:nth-of-type(2) {
  margin: 16px 0;
}

label, input, textarea {
  padding: 8px;
}

label, [placeholder] {
  color: #555;
}

label i {
  margin: 0 10px 0 0;
}

.field:focus-within label {
  color: #000;
  letter-spacing: 2px;
}

input, textarea {
  background: rgba(255, 255, 255, 0.5);
  border: none;
  border-radius: 4px;
  box-shadow: 0 8px 6px -6px #555;
}
input:focus, textarea:focus {
  background: white;
  box-shadow: none;
}

textarea {
  resize: none;
}
textarea::-webkit-scrollbar {
  width: 0;
}

.button {
  background: #2f4ad0;
  margin: 16px 0 50px 0;
  padding: 8px 16px;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  box-shadow: 0 8px 6px -6px #555;
}
.button:hover {
  letter-spacing: 2px;
  box-shadow: none;
}

.social-media {
  display: flex;
  flex-flow: row wrap;
  justify-content: space-around;
}
:not(.social-media) {
  font-size: 14px;
}
.social-media span {
  font-size: 16px;
}
.social-media span .fas {
  margin: 0 0 0 10px;
}
.social-media a {
  color: #000;
  font-size: 20px;
}

@media (max-width: 425px) {
  form {
    width: 100%;
  }
}
</style>

app/views/mboards/_mboard.html.erb
<div id="<%= dom_id mboard %>">
<div class="card-list">
  
  <div class="card-list__item card card--cacoo">
    <img class="card__thumbnail" src="https://nulab-inc.com/app/assets/img/blog/thumb_blog_cacoo.png" alt="Cacoo" />
    <div class="card__content">
      <h2 class="card__heading"><%= mboard.name %></h2>
      <p class="card__text"><%= mboard.body %></p>
    </div>
  </div>
  
</div>

</div> 

<style>
  .card--cacoo {
  order: 0;
}

.card--nulab {
  order: 0;
}

.card--backlog {
  order: 0;
}

.card-list {
  display: flex;
}
.card-list__item {
  width: 300px;
  margin: 15px;
}

.card {
  background-color: #f0f0f0;
}
.card__thumbnail {
  max-width: 100%;
  height: auto;
}
.card__content {
  padding: 15px;
}
.card__heading, .card__text {
  color: #75768b;
}
.card__heading {
  margin-top: 0;
  margin-bottom: 10px;
  font-size: 22px;
}
.card__text {
  margin-top: 0;
  font-size: 14px;
}
</style>

app/views/mboards/edit.html.erb
<br><br>

<h1 align="center">Editing mboard</h1>

<%= render "form", mboard: @mboard %>

<br>
 
<div>
  <%= link_to "Back to mboards", project_mboards_path(@mboard.project), class:"button-4" %>
</div>

<style>
.button-4 {
  text-decoration: none;
  appearance: none;
  background-color: #FAFBFC;
  border: 1px solid rgba(27, 31, 35, 0.15);
  border-radius: 6px;
  box-shadow: rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 1px 0 inset;
  box-sizing: border-box;
  color: #24292E;
  cursor: pointer;
  display: inline-block;
  font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
  font-size: 14px;
  font-weight: 500;
  line-height: 20px;
  list-style: none;
  padding: 6px 16px;
  position: relative;
  transition: background-color 0.2s cubic-bezier(0.3, 0, 0.5, 1);
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
  white-space: nowrap;
  word-wrap: break-word;
}

.button-4:hover {
  background-color: #F3F4F6;
  text-decoration: none;
  transition-duration: 0.1s;
}

.button-4:disabled {
  background-color: #FAFBFC;
  border-color: rgba(27, 31, 35, 0.15);
  color: #959DA5;
  cursor: default;
}

.button-4:active {
  background-color: #EDEFF2;
  box-shadow: rgba(225, 228, 232, 0.2) 0 1px 0 inset;
  transition: none 0s;
}

.button-4:focus {
  outline: 1px transparent;
}

.button-4:before {
  display: none;
}

.button-4:-webkit-details-marker {
  display: none;
}

</style>

app/views/mboards/index.html.erb
<br><br>
<%= link_to  "Back", project_path(@project), class: "button-6"%>
<%= link_to "New Message", new_project_mboard_path(@project), class:"button-5", style: "float: right" %>
<br><br> 
<h1>Message Board</h1>

<div id="mboards">
  <% @mboards.each do |mboard| %>
      <%= link_to  mboard, style: "text-decoration: none"  do %>
    <%= render mboard %>
    <% end %>
  <% end %>
</div>

<style>
.button-6 {
  align-items: center;
  background-clip: padding-box;
  background-color: #999999;
  border: 1px solid transparent;
  border-radius: .25rem;
  box-shadow: rgba(0, 0, 0, 0.02) 0 1px 3px 0;
  box-sizing: border-box;
  color: #fff;
  cursor: pointer;
  display: inline-flex;
  font-family: system-ui,-apple-system,system-ui,"Helvetica Neue",Helvetica,Arial,sans-serif;
  font-size: 16px;
  font-weight: 600;
  justify-content: center;
  line-height: 1.25;
  margin: 0;
  min-height: 3rem;
  padding: calc(.875rem - 1px) calc(1.5rem - 1px);
  position: relative;
  text-decoration: none;
  transition: all 250ms;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: baseline;
  width: auto;
}

.button-6:hover,
.button-6:focus {
  background-color: #999999;
  box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px;
}

.button-6:hover {
  transform: translateY(-1px);
}

.button-6:active {
  background-color: #c85000;
  box-shadow: rgba(0, 0, 0, .06) 0 2px 4px;
  transform: translateY(0);
}

.button-5 {
  align-items: center;
  background-clip: padding-box;
  background-color: #fa6400;
  border: 1px solid transparent;
  border-radius: .25rem;
  box-shadow: rgba(0, 0, 0, 0.02) 0 1px 3px 0;
  box-sizing: border-box;
  color: #fff;
  cursor: pointer;
  display: inline-flex;
  font-family: system-ui,-apple-system,system-ui,"Helvetica Neue",Helvetica,Arial,sans-serif;
  font-size: 16px;
  font-weight: 600;
  justify-content: center;
  line-height: 1.25;
  margin: 0;
  min-height: 3rem;
  padding: calc(.875rem - 1px) calc(1.5rem - 1px);
  position: relative;
  text-decoration: none;
  transition: all 250ms;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: baseline;
  width: auto;
}

.button-5:hover,
.button-5:focus {
  background-color: #fb8332;
  box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px;
}

.button-5:hover {
  transform: translateY(-1px);
}

.button-5:active {
  background-color: #c85000;
  box-shadow: rgba(0, 0, 0, .06) 0 2px 4px;
  transform: translateY(0);
}
</style>

app/views/mboards/new.html.erb
<br><br>
<h1 align="center">New mboard</h1>

<%= render "form", mboard: @mboard %>

<br>

<div>
  <%= link_to "Back to mboards", project_mboards_path(@pr), class:"button-4" %>
</div>

<style>
.button-4 { 
  text-decoration: none;
  appearance: none;
  background-color: #FAFBFC;
  border: 1px solid rgba(27, 31, 35, 0.15);
  border-radius: 6px;
  box-shadow: rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 1px 0 inset;
  box-sizing: border-box;
  color: #24292E;
  cursor: pointer;
  display: inline-block;
  font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
  font-size: 14px;
  font-weight: 500;
  line-height: 20px;
  list-style: none;
  padding: 6px 16px;
  position: relative;
  transition: background-color 0.2s cubic-bezier(0.3, 0, 0.5, 1);
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
  white-space: nowrap;
  word-wrap: break-word;
}

.button-4:hover {
  background-color: #F3F4F6;
  text-decoration: none;
  transition-duration: 0.1s;
}

.button-4:disabled {
  background-color: #FAFBFC;
  border-color: rgba(27, 31, 35, 0.15);
  color: #959DA5;
  cursor: default;
}

.button-4:active {
  background-color: #EDEFF2;
  box-shadow: rgba(225, 228, 232, 0.2) 0 1px 0 inset;
  transition: none 0s;
}

.button-4:focus {
  outline: 1px transparent;
}

.button-4:before {
  display: none;
}

.button-4:-webkit-details-marker {
  display: none;
}

</style>

app/views/mboards/show.html.erb
<%= render @mboard %>
<br>
<div>
  <%= link_to "Back to mboards", project_mboards_path(@mboard.project_id), class:"button-20" %>
  <%= link_to "Edit this mboard", edit_mboard_path(@mboard) , class: "button-21", style: "margin-left: 540px"%> 
  <%= button_to "Destroy this mboard", @mboard, method: :delete, class: "button-22", style: "float: right; margin-top: -41px"  %>
</div>

<br><br><br>
 
<div class="container">
	<div class="container__item">
    <%= form_with(model: @mb, class: "form") do |form| %>
      <%= form.text_field :body, class:"form__field"%>
		  <%= form.text_field :mboard_id, type: :hidden %>
      <%= form.submit "Add", class:"btn btn--primary btn--inside uppercase"%>
    <% end %>
	</div>
<div id="mbs">
<% @mbs.each do |message| %>

<p><%= message.body %></p>

<% if message.body %>
 <%= link_to "Destroy this mboard", message, "data-turbo-method": :delete %>
  
<% end %>


<% end %>
</div>
</div>

<style>
:root {
  background: #f5f6fa;
  color: #9c9c9c;
  font: 1rem "PT Sans", sans-serif;
}

html,
body,
.container {
  height: 100%;
}

a {
  color: inherit;
}
a:hover {
  color: #7f8ff4;
}

.container {
  flex-direction: column;
  align-items: left;
  justify-content: center;
}

.uppercase {
  text-transform: uppercase;
}

.btn {
  display: inline-block;
  background: transparent;
  color: inherit;
  font: inherit;
  border: 0;
  outline: 0;
  padding: 0;
  transition: all 200ms ease-in;
  cursor: pointer;
}
.btn--primary {
  background: blue;
  color: #fff;
  box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1);
  border-radius: 2px;
  padding: 12px 36px;
}
.btn--primary:hover {
  background: #6c7ff2;
}
.btn--primary:active {
  background: #7f8ff4;
  box-shadow: inset 0 0 10px 2px rgba(0, 0, 0, 0.2);
}
.btn--inside {
  margin-left: -96px;
}

.form__field {
  width: 360px;
  background: #fff;
  color: #a3a3a3;
  font: inherit;
  box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1);
  border: 0;
  outline: 0;
  padding: 22px 18px;
}


.button-22 {
  text-decoration: none;
  appearance: button;
  background-color: #CF4141;
  background-image: linear-gradient(180deg, rgba(255, 255, 255, .15), rgba(255, 255, 255, 0));
  border: 1px solid #CF4141;
  border-radius: 1rem;
  box-shadow: rgba(255, 255, 255, 0.15) 0 1px 0 inset,rgba(46, 54, 80, 0.075) 0 1px 1px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: Inter,sans-serif;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.5;
  margin: 0;
  padding: .5rem 1rem;
  text-align: center;
  text-transform: none;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-22:focus:not(:focus-visible),
.button-22:focus {
  outline: 0;
}

.button-22:hover {
  background-color: #CF4141;
  border-color: #CF4141;
}

.button-22:focus {
  background-color: #413FC5;
  border-color: #3E3BBA;
  box-shadow: rgba(255, 255, 255, 0.15) 0 1px 0 inset, rgba(46, 54, 80, 0.075) 0 1px 1px, rgba(104, 101, 235, 0.5) 0 0 0 .2rem;
}

.button-22:active {
  background-color: #CF4141;
  background-image: none;
  border-color: #CF4141;
  box-shadow: rgba(46, 54, 80, 0.125) 0 3px 5px inset;
}

.button-22:active:focus {
  box-shadow: rgba(46, 54, 80, 0.125) 0 3px 5px inset, rgba(104, 101, 235, 0.5) 0 0 0 .2rem;
}

.button-22:disabled {
  background-image: none;
  box-shadow: none;
  opacity: .65;
  pointer-events: none;
}


.button-21 {
  text-decoration: none;
  appearance: button;
  background-color: #F4CE5B;
  background-image: linear-gradient(180deg, rgba(255, 255, 255, .15), rgba(255, 255, 255, 0));
  border: 1px solid #F4CE5B;
  border-radius: 1rem;
  box-shadow: rgba(255, 255, 255, 0.15) 0 1px 0 inset,rgba(46, 54, 80, 0.075) 0 1px 1px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: Inter,sans-serif;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.5;
  margin: 0;
  padding: .5rem 1rem;
  text-align: center;
  text-transform: none;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-21:focus:not(:focus-visible),
.button-21:focus {
  outline: 0;
}

.button-21:hover {
  background-color: #F4CE5B;
  border-color: #F4CE5B;
}

.button-21:focus {
  background-color: #413FC5;
  border-color: #3E3BBA;
  box-shadow: rgba(255, 255, 255, 0.15) 0 1px 0 inset, rgba(46, 54, 80, 0.075) 0 1px 1px, rgba(104, 101, 235, 0.5) 0 0 0 .2rem;
}

.button-21:active {
  background-color: #F4CE5B;
  background-image: none;
  border-color: #F4CE5B;
  box-shadow: rgba(46, 54, 80, 0.125) 0 3px 5px inset;
}

.button-21:active:focus {
  box-shadow: rgba(46, 54, 80, 0.125) 0 3px 5px inset, rgba(104, 101, 235, 0.5) 0 0 0 .2rem;
}

.button-21:disabled {
  background-image: none;
  box-shadow: none;
  opacity: .65;
  pointer-events: none;
}


.button-20 {
  text-decoration: none;
  appearance: button;
  background-color: #999999;
  background-image: linear-gradient(180deg, rgba(255, 255, 255, .15), rgba(255, 255, 255, 0));
  border: 1px solid #999999;
  border-radius: 1rem;
  box-shadow: rgba(255, 255, 255, 0.15) 0 1px 0 inset,rgba(46, 54, 80, 0.075) 0 1px 1px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: Inter,sans-serif;
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.5;
  margin: 0;
  padding: .5rem 1rem;
  text-align: center;
  text-transform: none;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-20:focus:not(:focus-visible),
.button-20:focus {
  outline: 0;
}

.button-20:hover {
  background-color: #999999;
  border-color: #999999;
}

.button-20:focus {
  background-color: #413FC5;
  border-color: #3E3BBA;
  box-shadow: rgba(255, 255, 255, 0.15) 0 1px 0 inset, rgba(46, 54, 80, 0.075) 0 1px 1px, rgba(104, 101, 235, 0.5) 0 0 0 .2rem;
}

.button-20:active {
  background-color: #999999;
  background-image: none;
  border-color: #999999;
  box-shadow: rgba(46, 54, 80, 0.125) 0 3px 5px inset;
}

.button-20:active:focus {
  box-shadow: rgba(46, 54, 80, 0.125) 0 3px 5px inset, rgba(104, 101, 235, 0.5) 0 0 0 .2rem;
}

.button-20:disabled {
  background-image: none;
  box-shadow: none;
  opacity: .65;
  pointer-events: none;
}
</style>